name: Django CI with Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the code
    - name: Checkout Code
      uses: actions/checkout@v4

    # Step 2: Set up Docker
    - name: Log in to DockerHub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    # Step 3: Build the Docker image
    - name: Build Docker Image
      run: docker build -t deploo .

    # Step 4: Run the Docker container
    - name: Run Docker Container
      run: docker run -d -p 8000:8000 deploo

    # Step 5: Run Tests in Docker Container
    - name: Run Tests
      run: docker exec $(docker ps -q -f ancestor=deploo) python manage.py test
# Step 6: Push the Docker image to DockerHub
    - name: Push to DockerHub
      run: docker tag deploo ${{ secrets.DOCKER_USERNAME }}/deploo:latest
           docker push ${{ secrets.DOCKER_USERNAME }}/deploo:latest
